name: Java CI with Gradle V0.1

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test domain-mysql with Gradle
        run: |
          cd domain-mysql
          chmod +x ./gradlew
          ./gradlew test

      - name: Set up domain-mongodb test application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./domain-mongodb/src/test/resources/application.yml
        env:
          jasypt.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Test domain-mongodb with Gradle
        run: |
          cd domain-mongodb
          chmod +x ./gradlew
          ./gradlew test

      - name: Set up member-api application-common.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./member-api/src/main/resources/application.yml
        env:
          jasypt.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Build member-api with Gradle
        run: |
          cd member-api
          chmod +x ./gradlew
          ./gradlew build
